#!/usr/bin/env bash
# writen by Ivan c00kiemon5ter Kanakarakis ~ <ivan.kanak[at]gmail.com>

path="$(dirname "$0")"
sugar="${path}/sugar.conf"
donuts="${path}/donuts"
arg0="$1"

declare -A servers
declare -A allnames

[[ -r "${sugar}" ]] && source "${sugar}" ||  {
    printf -- "error: cannot read configuration: %s\n" "${sugar}"
    exit 1
}
[[ -r "${donuts}" ]] || {
    printf -- "error: cannot read commands: %s\n" "${donuts}"
    exit 1
}

: "${prefix:="${HOME}/irc"}"
: "${nickname:=pancakes}"
: "${realname:=cookiebot}"
: "${mode:=+iw}"
: "${hostname:=cookiebox}"
: "${servername:=biscuit}"
: "${port:=6667}"

/bin/mkdir -p "${prefix}" || {
    printf -- "error: cannot create prefix: %s\n" "${prefix}"
    exit 1
}

for server in "${!servers[@]}"; do
    exec {ircfd}<> "${prefix}/${server}.errors.log" 2>&${ircfd}-

    if ! exec {ircfd}<> /dev/tcp/${server}/${port}; then
        printf -- "unable to connect to server: %s:%d\n" "${server}" "${port}"
        continue
    fi

    printf -- "PASS %s\n" "${passwd}" >&${ircfd}
    printf -- "NICK %s\n" "${nickname}" >&${ircfd}
    printf -- "MODE %s %s\n" "${nickname}" "${mode}" >&${ircfd}
    printf -- "USER %s %s %s :%s\n" "${nickname}" "${hostname}" "${servername}" "${realname}" >&${ircfd}

    for channel in ${servers[${server}]}; do
        printf -- "JOIN %s\n" "${channel}" >&${ircfd}

        fifo="${prefix}/${server}_${channel#\#}.in"
        /bin/mkfifo "${fifo}" || {
            printf -- "error: cannot create fifo: %s\n" "${fifo}"
            continue
        }

        {   exec {fffd}<>"${fifo}"

            trap 'exec {fffd}>&-; /bin/rm -f "${fifo}"; /bin/rm "${prefix}/${server}_${channel#\#}.names"' EXIT

            printf -- "ACTION %s\n" "Heya peoples :]" >&${fffd}

            while read -r -u ${fffd}
            do printf -- "PRIVMSG %s :%s\n" "${channel}" "${REPLY}" >&${ircfd}
            done
        } &

        chanpids+=($!)
    done

    {   trap 'printf -- "QUIT :%s will be back ..\n" "${nickname}" >&${ircfd};
        exec {ircfd}>&-; for pid in "${chanpids[@]}"; do /bin/kill "${pid}"; done;' EXIT

        while read -r -u ${ircfd}; do
            set -- ${REPLY//$'\r'/}
            [[ "$arg0" == "debug" ]] && echo "${REPLY}"

            [[ "$1" == "PING" ]] && printf -- "PONG %s\n" "$2" >&${ircfd} && continue
            
            [[ "$2" == "353" ]] && echo $(echo ${REPLY} | /bin/cut -d':' -f3 | /bin/sed 's/@//' | /bin/sed "s/${nickname} //") > "${prefix}/${server}_${channel#\#}.names"

            read -r who did where what <<< "${REPLY%}"
            {  [[ "${did}" == "PART" ]] && what=':!PART'; } || \
            {  [[ "${did}" == "JOIN" ]] && what=':!JOIN'; } || \
               [[ "${did}" == "PRIVMSG" ]] || continue

            printf -- "%s\n" "${REPLY}" >> "${prefix}/${server}_${where#*\#}_$(date +"%F").log"

            [[ "${who%\!*}" != ":${nickname}" && "${what}" =~ ^:\! ]] || continue
            exec "${donuts}" "${what#:\!}" "${where#:}" "${who#:}" "${nickname}" "${server}" "${prefix}" | /bin/cut -c -255 >&${ircfd} &
        done
    } &
    
    
    {
		while true; do
			printf -- "NAMES %s \n" "${channel}" >&${ircfd}
			sleep 60
		done
	} &
done

